# we need to tell Travis that sudo is needed
sudo: required
# Travis needs to know that we will be using docker
services:
    - docker

# build our stuff so we can do testing
before_install:
    - docker build -t d0minar/docker-react -f Dockerfile.dev .

# commands we want Travis to run to do out testing
# Travis will watch those and if command returns
# anything other than 0, it will count it as failed
# NOTE: default npm run test does not exit like Travis is expecting
# NOTE: it waits for input. to deal with that we add "-- --coverage"
script:
    - docker run -e CI=true d0minar/docker-react npm run test -- --coverage

# NOTE: get region from the beanstalk url that you get for your app
# NOTE: look up bucket_name in S3 section of AWS, look for elasticbeanstalk-eu-west-2
deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-657270835947"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"